### ISSUE TITLE
Regarding Pact wizard

### ISSUE THREAD

**Issue by Mythalar** [kreaddy/MysticalMayhem#10]
Hey,

First things first, tank you for you work, Falgellant and Pac wizard archetypes ere very nice for my runs so far ok (Meteor swarm too...) !

One question though  the Pact wizard spontaneously casting, while nice, is not as useful as it could since it does not allow to cast patron spells with metamagic. 
So you have still to memorize those spells to benefit from the -1 metamagic modifier (even though at least they are considered "heighened" if converted from higher spell leveled).

Would it be possible to allow :

- spontaneously casts of the modified patron spells written in the spell book at corresponding spell level (and heighened modified versions at higher level) ?
- or fully allow to spontaneously cast any metamagic variation possible at each spell level, based on the metamagic feats you have ?

The latter seems to be the way to go by raw and, if memory serves, was actually implemented in the Call of the Wilds Kingmaker mod.
(I guess it could clog the UI though)

The first one would be really useful and a nice compromise.

**Comment by kreaddy** [comment]
I don't think pact wizards are supposed to be able to spontaneously add metamagic with patron spells they have not memorized. RAW doesn't explicity say they can't but it doesn't say they can either.

My personal opinion is that the archetype is already overloaded as it is and there's also the issue of the UI—certain levels, especially the higher ones, have so many spells the menu actually cuts off. If I could nest variants it would solve the problem but I can't and changing that is a can of worms I really don't want to open.

**Comment by Mythalar** [comment]
Ok thanks nonetheless.
I readily agree for the UI part, and RAW does not forbid it but there seems to be a consensus on this on the paieo forums.
Well the "hook variants" method would have been perfect but if not feasible I understand:)
