### ISSUE TITLE
bugreport missing description

### ISSUE THREAD

**Issue by kjk001** [kreaddy/MysticalMayhem#12]
please see attached screenshot both wind and waves are affected:
![225744383-7fbb60e0-065a-4d74-a96b-e041b15eee71](https://user-images.githubusercontent.com/121681604/225877995-e3031d46-fa95-4852-9e3d-53875201452e.png)

**Comment by kreaddy** [comment]
Good catch, it was a typo. Fixed for next release.

**Comment by kjk001** [comment]
you should give that praise to @Nerin3, he actually caught it and just accidentally reported it to us rather than you.
I just figured out the actual source afterwards.
