### ISSUE TITLE
bug：Draconic Malice has no effect

### ISSUE THREAD

**Issue by HerryZheng8** [kreaddy/MysticalMayhem#16]
Draconic Malice has no effect, I used this spell when Demoralize monsters with Greater Heroism, it still showed immunity

**Comment by kreaddy** [comment]
What was the target?

**Comment by HerryZheng8** [comment]
A Mythic Oolioddroo ShadowWalker, which I added Greater Heroism buff to using the toy box

**Comment by HerryZheng8** [comment]
I saw that there was a debuff description in the Localization file that was supposed to be in the monster when I used it, but I didn't see this effect when I used it.

**Comment by kreaddy** [comment]
The way it works, you get an aura. This aura is only melee range. When an enemy enters it they get a saving throw to ignore the effect. If they leave the aura and then re-enter, they get another saving throw to see if it applies again.

Undead and constructs are never affected regardless.

**Comment by HerryZheng8** [comment]
Yes, I used Demoralize between close to monsters and melee, it had no effect

**Comment by HerryZheng8** [comment]
I'll get you a screenshot of the game later

**Comment by HerryZheng8** [comment]
![QQ截图20230330195858](https://user-images.githubusercontent.com/84825552/228829150-6f1d240b-2435-4fe5-939d-3ede7454a7f0.jpg)

**Comment by HerryZheng8** [comment]
Just like that, even when I get close to the monster, there is no aura effect on its body

**Comment by HerryZheng8** [comment]
When I remove the BUFF, the monsters will be shaken normally
![QQ截图20230330200323](https://user-images.githubusercontent.com/84825552/228830057-fa1729f4-ec1a-4166-9a40-1b84f5dbe518.jpg)

**Comment by kreaddy** [comment]
All right I will investigate.

**Comment by HerryZheng8** [comment]
Thank you
![02AE9551](https://user-images.githubusercontent.com/84825552/228838072-12f436bc-ca53-49b1-963e-b49c625045b3.png)

**Comment by kreaddy** [comment]
This should be fixed now. I'm still not entirely sure how I managed to break it in the first place when it worked fine in my initial tests, but oh well.
