### ISSUE TITLE
Flagellant Proficiencies cannot offer the features

### ISSUE THREAD

**Issue by a234106261** [kreaddy/MysticalMayhem#21]
Flagellant Proficiencies still correctly allow the chara to use the armor, shield and weapons, but cannot provide the features
Chara cannot learn medium armor proficiency or even the light armor proficiency

**Comment by kreaddy** [comment]
It's less a bug and more that I completely forgot about that. Anyways, that's fixed for next release, just give yourself the features with Toybox for the time being.
