### ISSUE TITLE
Latest version conflicts with another mod called Dark Codex.

### ISSUE THREAD

**Issue by Merilirem** [kreaddy/MysticalMayhem#22]
The 2.0 version was fine but now the game won't load anymore with Dark Codex also running. Which is a shame since they previously worked fine together. 

Also I noticed the game not exiting correctly even if this was the only mod installed. It does the yellow triangle error popup thing every time I try to close it. Not a big deal since it still seems to work but still.

**Comment by kreaddy** [comment]
Will investigate this evening when I come back from work.

**Comment by kreaddy** [comment]
Well, anyway, this should be fixed now.
