### ISSUE TITLE
Draconic Malice isn't Casting

### ISSUE THREAD

**Issue by zerotheglitch** [kreaddy/MysticalMayhem#23]
Like it states draconic malice is not casting at all, it's not even using a spell slot some i'm not sure if its mod incompatability with some features or something else entirely since theres a few other buffs that mess up also. but i posted a backup of my vortex modlist but some of the mods I believe aren't included in it.

They Are: Added Feats, Additional Hotkeys, Advanced Developer mode, Allow Modded Achievements, Alternate human traits, Auto Mount, Boat Boat Boat, Bubble Buffs, Bubble tweaks, Buff Bot, Character Options+, Cleaner, Combat Relief (Updated), Custom Npc Portraits, Dark Codex, Enduring Reworks, Expanded Content, Finnean Tweaks, Isekai Mod, Kinetic Archetype, Kineticist Elements Expanded, Levelable Aivu, Level Up Plan Customizer, Martial Excellence, Mewsifier Console, Microscopic Expansion (I Am Getting an error on this one for an alchemist infusion patch that i can't disable), Mod Menu, More Bulk Sell, More Relic Info, Multiple Archetypes, Mystical Mayhem, Mythic Arcanist, Mythic Path Power Swapper, Mythic Spellbook tweaks, No Film Grain, Phoenix's Cantrips + More Cantrips, Puzzle Skip, Snap Shot Approach, Spell Pouch, Spellbook Merge, Swashbuckler Class, All Tabletop tweaks Main Mods, Toggleable Throwing Weaponry, Tome of the Firebird, Use Until Healed, Visual Adjustments 2 (Disables),Weapon focus Plus, Woljif Romance Mod, WOTR Inventory Tweak (Quick Cast), Wotr Resource Unification, And Wotr Character Display.

[Manual_21_Shield_Maze__15_Arodus__VIII__4715__21_26_53.zip](https://github.com/kreaddy/MysticalMayhem/files/12286779/Manual_21_Shield_Maze__15_Arodus__VIII__4715__21_26_53.zip)
[Vortex_Modlist_Backup.txt](https://github.com/kreaddy/MysticalMayhem/files/12286787/Vortex_Modlist_Backup.txt)
[Player.log](https://github.com/kreaddy/MysticalMayhem/files/12286758/Player.log)
[GameLog.txt](https://github.com/kreaddy
[GameLogFull.txt](https://github.com/kreaddy/MysticalMayhem/files/12286870/GameLogFull.txt)
/MysticalMayhem/files/12286869/GameLog.txt)

**Comment by kreaddy** [comment]
I can't reproduce your issue and your logs show no error with my mod, only with Microscopic Expansion and something called Share Companion Spells.

It would make no sense for Draconic Malice alone to fail casting because it's just a standard aura spell. Unless you have a mod changing the way aura spells work (in which case other spells like Archon's Aura are likely broken too) there's something else going on with your game here.

I am not going to install your huge modlist just to search blindly for something so unless you manage to give me more information there's nothing I can do.

**Comment by kreaddy** [comment]
> since i made a new game with no mods enable, and all would be well until I enabled this mod and the mod menu

@BlissfulDog, if you can reproduce this with only my mod then give me all the information you can: your class, and what features from this mod you are using. Also give me logs.

**Comment by zerotheglitch** [comment]
in my case i believe it was a problem with personal aura spells in general some work some don't it might be that i re-enabled a setting or mod that i disabled originally, i also noticed that on microscopic the fix page doesn't have settings on it same with a few other mods
