### ISSUE TITLE
Flagellant's greater mortified spellcasting doesn't work

### ISSUE THREAD

**Issue by HeroOfCows** [kreaddy/MysticalMayhem#3]
Lower tier mortified spellcasting works as described- swift action, adds temporary buff, casting a spell does some damage to me and gets either a CL or DC bump. Greater mortified consumes a swift action but otherwise does not appear to do anything.

**Comment by kreaddy** [comment]
It's supposed to replace the regular Mortified Spellcasting (so you would stiill have only 2 abilities in the menu) but indeed it doesn't. Weird, I'm sure it _used_ to work at some point. Working on it.
