### ISSUE TITLE
About Localization

### ISSUE THREAD

**Issue by Kifusou** [kreaddy/MysticalMayhem#5]
I know nothing about code so i simply trans the value in the enGB.json into chinese, like "Value": "Material Freedom" to "Value": "材料自由", and save as another file called zhCN.json, but this is not effective, in-game text is still english.
Would you please show me what is the correct methods？Thank you！Like your mod.

**Comment by kreaddy** [comment]
Yes, this how it works. I just re-tested it to make sure and it works even if you switch locale during the game. I don't know why it doesn't for you, are you sure you placed the file correctly in the Localization folder?

**Comment by Kifusou** [comment]
I try again and this time i trans just one or two lines of value instead of trans all the value and save, it works. lol
I have seen this before when i trans other mod. if i trans too much and save, it will not work but throw out a BROKEN_Localizationpack.json to the mod folder when open the game. I don't know why. So i can only trans a little and save then a little and save. Thank you for remind me this strange thing(i even don't know if this a bug or my incorrect operation). Anyway i will keep up my translating a little and save. Slow but effective at least. lol

**Comment by kreaddy** [comment]
All right, I'll close this issue then. Feel free to make a pull request or give me the localization file if you want me to include it in the release directly one you're done 👍

**Comment by Kifusou** [comment]
I have done the work and tested，this is the chinese localization file for 0.1.2c.
hope it works!
Also, in the enGB.json, the "MM_Shaman_Waves_Desc" and "MM_Shaman_Wind_Desc" lose a "20", and the "MM_S_Adnd_Stoneskin_Desc" should be right but the in-game text says it should be "MM_S_Andn_Stoneskin_Desc". I changed it to "Andn" in zhCN.json for that the in-game text can be read. But i still thought "Adnd" is right. Are they?
[zhCN.zip](https://github.com/kreaddy/MysticalMayhem/files/9879437/zhCN.zip)

**Comment by kreaddy** [comment]
Andn was a typo in the settings file. I corrected it in the English localization and in the file you gave me. And yeah I wasn't super consistent with the 20s, probably because I made Waves and Wind a few weeks after the previous spirits. Anyway, good job thank you! I'll test a bit more and update the mod.

**Comment by Kifusou** [comment]
Thank you, and this is the newest file, adjust some translation to be consistent with the guide book translation, the adnd also fixed
[zhCN.zip](https://github.com/kreaddy/MysticalMayhem/files/9880654/zhCN.zip)

**Comment by kreaddy** [comment]
Thanks! I pushed a release with it.
