### ISSUE TITLE
Material Freedom turns off Ecclesithurge casting

### ISSUE THREAD

**Issue by JamesEhren** [kreaddy/MysticalMayhem#7]
Experienced on 2.0.4j, but may be an issue on the previous build as well.

Choosing any of the four options for the Material Freedom mythic ability immediately turns off Ecclesitheurge casting.  The spells become grayed out in the popup spellbook and ability bars.  Clicking on one will only expand the spontaneous cure/bonded item icon selection. Clicking the spontaneous cure icon will result in a battle log message of "Unavailable" while clicking on the bonded item icon does nothing.

Using Toybox to remove the feature or Repsec to roll back a mythic level immediately re-enables Ecclesitheurge casting.

**Comment by kreaddy** [comment]
Will investigate but I won't have much time before the weekend. In any case this is really weird, as Material Freedom doesn't interact at all with Ecclesitheurge features. To be clear: the issue only appears with Ecclesitheurge? It doesn't affect any other caster (particularly Pact Wizard)?

**Comment by JamesEhren** [comment]
Started a couple new games and toybox'd my way up to 6+1 to check.  Same issue with a Pact Wizard, standard Sorcerer, and standard Alchemist.  I stopped there.  Spells gray out after taking MF, and re-enable after rolling back the mythic level with respec or de-featuring with toybox.

**Comment by kreaddy** [comment]
This is fixed now.
